# Clock from Gazebo to ROS
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Conveyor belt speed command
- ros_topic_name: "/gazebo/conveyor_belt/cmd_vel"
  gz_topic_name: "/model/conveyor_belt/link/base_link/track_cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Solenoid command
- ros_topic_name: "/gazebo/pusher/cmd_pos"
  gz_topic_name: "/model/solenoid_pusher/joint/slider_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Camera 1 stream (vision node)
- ros_topic_name: "/camera1/image_raw"
  gz_topic_name: "model/camera1/raw_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Camera 2 stream (check node)
- ros_topic_name: "/camera2/image_raw"
  gz_topic_name: "model/camera2/raw_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Objects position logging
- ros_topic_name: "/gazebo/spawned_objects/odometry"
  gz_topic_name: "/gazebo/spawned_objects/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Object deletion topic
- service_name: "/world/inspection_system/remove"
  ros_type_name: "ros_gz_interfaces/srv/DeleteEntity"
  gz_req_type_name: "gz.msgs.Entity"
  gz_rep_type_name: "gz.msgs.Boolean"